[package]
name = "arbitrage"
version = "0.1.0"
description = "Solana on-chain arbitrage program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "arbitrage"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

# Raydium CLMM CPI
# raydium-clmm = { git = "https://github.com/raydium-io/raydium-clmm", features = ["cpi"] }

[dev-dependencies]
anchor-client = "0.29.0"
